### ISSUE TITLE
Voronoi Construction (Buffer Region does bias LagDist)

### ISSUE THREAD

**Issue by RobinCGN** [C-C-A-A/CologneProtocol-R#16]
When comparing the voronois constructed with R and the voronoi polygons constructed with QGIS it becomes obvious that the R polygons are larger than the QGIS voronoi diagrams. This leads to different bounding boxes, lag distances and maxsearch distances:

![grafik](https://user-images.githubusercontent.com/58631164/78777505-f3796d80-7999-11ea-89ce-0c6b1b15ee14.png)

QGIS (blue), R (red)

One can reproduce the R voronoi polygon construction in QGIS by adding a buffer region of 10 %:
![grafik](https://user-images.githubusercontent.com/58631164/78777758-6aaf0180-799a-11ea-9737-ce77a98db26e.png)

QGIS with 10 % buffer region (blue), R (red). 

Therefore, the "deldir" function in our script seems to use a buffer region of 10 %.

We should seek a work-around to make both procedures/results more homogenous!

**Comment by VicluUiB** [comment]
Hi,

What would be the way to go if one wants R to generate a voronoi-diagram that buffers slightly beyond ones occurrence records? I agree that by extending the bounding box of the calculation one might introduce more problems. However, my experience from not adjusting the size of the voronoi diagram is that isolines that touch on the edges of the kriging raster will be broken, in other words, not closed. This translates into faulty polygons if one then later on goes on to simply just converting the isolines to polygons. The end result is that some sites will not be registered in the final plots (i.e. percentage per isoline etc). 

I don't know what the isolines look like after they are produced in the r-script, but it could be worth to investigate as, if they too are faulty, then it is not clear if the resulting plots generated by the merged polygons are accurate either.
